---
name: Coverage
on:
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run tests
        run: go test -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Launch golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
